### ISSUE TITLE
Dlib not installing using pip

### ISSUE THREAD

**Issue by harshitbansall** [akshitagupta15june/Face-X#1079]
# Describe the bug
Many Filters in the Snapchat folder are Using <code>dlib</code> module. When I Tried to Install the dlib module using pip, It returned an Error. <br>
![Error](https://user-images.githubusercontent.com/24206423/156135889-92bf72f2-6fef-4431-819c-2b7be36e2246.png)

## I searched it on [Stackoverflow](https://stackoverflow.com/questions/41912372/dlib-installation-on-windows-10).
It guided me to download and install <code>cmake</code>. But still it is returning an error.

**Comment by akshitagupta15june** [comment]
Cool some contributors will look at your issue

**Comment by suvadityamuk** [comment]
Hi, would like to give this a shot. Could you assign it to me?

Also, @harshitbansall I just replicated your process to install `dlib` and it worked for me. 

I think its mainly because of the building stage, that it invoked an error. It was a pretty resource-intensive operation which nearly slowed down my computer, but it finally worked. I think its mainly because of some issue of running out of RAM during the wheel-building stage, that led to this error. I have shared my output below for your reference.

Possible solutions include:
1) Having a Swap partition (if you can shift to a Linux distro) which allows for bigger usage of memory from your hard-drive.
2) Build it yourself. Make your way to [`dlib`](https://github.com/davisking/dlib) and download it as a .zip file. Then use CMake to generate a build system and do it from scratch. Quite the long process.
3) Just wait out the build loop to finish. It's working alright, just needs time.

In most cases than not, that build loop is working but is a long one due to the size of the entire `dlib` module (Huge ML lib for C++). To get more granular/verbose updates, you might wanna append `-vvv` to your installation command, something like

`pip install -r requirements.txt -vvv`

Would love it if you can try doing the above, and maybe wait for at-least 10-15 minutes for the process to complete.

![image](https://user-images.githubusercontent.com/70141886/156150518-a0a57deb-9997-4f76-9db3-b05d7dad1241.png)

**Comment by akshitagupta15june** [comment]
Assigning to you @suvadityamuk

**Comment by akshitagupta15june** [comment]
@harshitbansall I hope you will look at the solutions provided by @suvadityamuk
